binop_separator = "Back"
brace_style = "PreferSameLine"
edition = "2021"
imports_indent = "Visual"
match_arm_blocks = false
match_block_trailing_comma = true
reorder_imports = true
use_field_init_shorthand = true
