[package]
name = "dash-spv-keychain"
version = "0.0.1"
description = "Library for interactions between OS Keychain"

edition = "2021"
publish = false

[dependencies]
ferment-macro = { git = "https://github.com/dashpay/ferment", package = "ferment-macro" }

[lib]
name = "dash_spv_keychain"
