[package]
name = "dash-spv-platform"
version = "0.0.1"
description = "Library for interactions with platform SDK"

edition = "2021"
publish = false

[dependencies]
dapi-grpc = { path = "../../platform/packages/dapi-grpc" }
dash-sdk = { path = "../../platform/packages/rs-sdk" }
drive = { path = "../../platform/packages/rs-drive" }
drive-proof-verifier = { path = "../../platform/packages/rs-drive-proof-verifier" }
ferment = { path = "../../ferment/ferment" }
ferment-macro = { path = "../../ferment/ferment-macro" }
http = { version = "0.2.12" }
platform-value = { path = "../../platform/packages/rs-platform-value" }
platform-version = { path = "../../platform/packages/rs-platform-version" }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
tokio-util = { version = "0.7.10" }

[build-dependencies]
ferment-sys = { path = "../../ferment/ferment-sys" }

[lib]
name = "dash_spv_platform"
