[package]
name = "dash-spv-platform"
version = "0.0.1"
description = "Library for interactions with platform SDK"

edition = "2021"
publish = false

[dependencies]
#ferment = { path = "../../ferment/ferment" }
#ferment-macro = { path = "../../ferment/ferment-macro" }
#dapi-grpc = { path = "../../platform/packages/dapi-grpc" }
#dash-sdk = { path = "../../platform/packages/rs-sdk" }
#drive = { path = "../../platform/packages/rs-drive" }
#drive-proof-verifier = { path = "../../platform/packages/rs-drive-proof-verifier" }
#platform-value = { path = "../../platform/packages/rs-platform-value" }
#platform-version = { path = "../../platform/packages/rs-platform-version" }
dapi-grpc = { git = "https://github.com/pankcuf/platform", branch = "test/ferment", package = "dapi-grpc" }
dash-sdk = { git = "https://github.com/pankcuf/platform", branch = "test/ferment", package = "dash-sdk" }
drive = { git = "https://github.com/pankcuf/platform", branch = "test/ferment", package = "drive" }
drive-proof-verifier = { git = "https://github.com/pankcuf/platform", branch = "test/ferment", package = "drive-proof-verifier" }
platform-value = { git = "https://github.com/pankcuf/platform", branch = "test/ferment", package = "platform-value" }
platform-version = { git = "https://github.com/pankcuf/platform", branch = "test/ferment", package = "platform-version" }
ferment = { git = "https://github.com/pankcuf/ferment", branch = "feat/reorg", package = "ferment" }
ferment-macro = { git = "https://github.com/pankcuf/ferment", branch = "feat/reorg", package = "ferment-macro" }
http = { version = "0.2.12" }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
tokio-util = { version = "0.7.10" }

[build-dependencies]
ferment-sys = { git = "https://github.com/pankcuf/ferment", branch = "feat/reorg", package = "ferment-sys", features = ["objc"] }
#ferment-sys = { path = "../../ferment/ferment-sys", features = ["objc"] }

[lib]
name = "dash_spv_platform"
