[target.aarch64-apple-ios]
rustflags = ["-C", "link-arg=-target", "-C", "link-arg=arm64-apple-ios15.0", "-C", "link-arg=-mios-version-min=15.0"]

[target.x86_64-apple-ios]
rustflags = ["-C", "link-arg=-target", "-C", "link-arg=x86_64-apple-ios15.0", "-C", "link-arg=-mios-simulator-version-min=15.0"]

[target.aarch64-apple-ios-sim]
rustflags = ["-C", "link-arg=-target", "-C", "link-arg=arm64-apple-ios15.0-simulator", "-C", "link-arg=-mios-simulator-version-min=15.0"]
