[package]
name = "dash-spv-macro"
version = "0.1.0"
description = "Macros for boilerplate"
edition = "2021"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.109", features = ["full", "visit-mut"] }
quote = "1.0.28"
